- name: Deploy Nginx using Helm via Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Add Bitnami Helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Deploy Nginx Helm chart
      kubernetes.core.helm:
        name: nginx-release-v2
        chart_ref: bitnami/nginx
        release_namespace: default
        create_namespace: true
        values_files:
          - values.yml
        state: present
